indent = "space"
indent_size = 2
semi = true
single_quote = true
trailing_comma = "es5"
print_width = 100
arrow_parens = "always"
end_of_line = "lf"
jsx_single_quote = true
bracket_spacing = true
bracket_same_line = false

[sortImports]
order = "asc"
internalPattern = ["@/*", "@klk/*"]
newlinesBetween = "always"
